resources:
- name: tiny-image
  type: docker-image
  source:
    repository: cloudfoundry/tiny
    tag: latest
    email: {{buildpacks-docker-user-email}}
    username: {{buildpacks-docker-username}}
    password: {{buildpacks-docker-password}}
- name: git-tiny
  type: git
  source:
    uri: git@github.com:pivotal/tiny.git
    branch: master
    private_key: {{tiny-ssh}}
- name: new-cves
  type: git
  source:
    uri: git@github.com:cloudfoundry/public-buildpacks-ci-robots
    branch: master
    paths: [ new-cve-notifications/ubuntu18.04.yml ]
    private_key: {{tiny-ssh}}

jobs:
- name: test-tiny
  plan:
  - get: git-tiny
    trigger: true
  - get: new-cves
    trigger: true
  - task: integration-test
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: pivotalnavcon/docker-go
      inputs:
      - name: git-tiny
      run:
        path: /bin/bash
        args:
        - -c
        - |
            set -eux -o pipefail
            source /opt/resource/common.sh
            sanitize_cgroups
            start_docker 3 3 "" ""

            apk add coreutils ncurses curl
            curl -#L https://github.com/bats-core/bats-core/archive/master.zip | unzip -
            bash bats-core-master/install.sh /usr/local

            cd git-tiny
            docker build -t tiny .
            bats -t ./tests/test.bats && bats -t ./tests/testapp.bats

- name: build-and-publish-tiny
  public: true
  plan:
    - get: git-tiny
      passed: [test-tiny]
      trigger: true
    - get: new-cves
      passed: [test-tiny]
      trigger: true
    - put: tiny-image
      params:
        build: git-tiny
        build_args:
          squash: squash
      attempts: 2
